### ISSUE TITLE
Document system package requirements

### ISSUE THREAD

**Issue by shuttle1987** [persephone-tools/persephone-web-API#102]
Various system packages must be installed, including:

* ffmpeg
* sox
* Kaldi for pitch features

**Comment by shuttle1987** [comment]
It seems like Kaldi is required in order to support functionality such as `filterbank_and_pitch` features

**Comment by oadams** [comment]
That is correct. For serious users, having the pitch features will be valuable if dealing with tonal languages (and often even if the languages aren't tonal), but it adds another step in the installation pipeline. Building these Kaldi binaries is straightforward though.
