### ISSUE TITLE
Annotating endpoints in API spec

### ISSUE THREAD

**Issue by aapeliv** [persephone-tools/persephone-web-API#112]
I'm generating a bunch of code from the `api_spec.yml` file. It'd be very useful to have some kind of annotations for each endpoint defining what kind of endpoint that is. Such as `listObjects` or `getObject`, etc. I think this could be done with tags.

**Comment by shuttle1987** [comment]
What benefits does this give you for the code-generation?

**Comment by aapeliv** [comment]
I'll make some template for each type of page; so a page to view a single audio file could be rendered to show each bit of info the API returns under a heading; whereas a page listing every audio file would have a table.

**Comment by aapeliv** [comment]
Was added in 211760dd83ff2db4155383200181a7b0c51168f0, but it's actual a royal pain in the ass, so can we revert it, please?

**Comment by shuttle1987** [comment]
I just reverted the tags changes in c0d045d698b0e0c6fcf2e0d11ea09e2f58872f36
