### ISSUE TITLE
Extra name property in transcriptionInformation?

### ISSUE THREAD

**Issue by aapeliv** [persephone-tools/persephone-web-API#122]
The `transcriptionInformation` definition contains a `name` to store the name of the file. But it also has `fileInformation` which contains another `name`. This doesn't seem to be uniform across other definitions (i.e. for audio).

**Comment by shuttle1987** [comment]
This is just some technical debt, the `fileInformation` API will be the only way file information will be stored going forward. The only thing left to figure out is how to represent the file information for a transcription if it's only stored in a database table and not in a file.
