### ISSUE TITLE
Validation errors don't conform to error spec

### ISSUE THREAD

**Issue by aapeliv** [persephone-tools/persephone-web-API#143]
Output is of this form:

```
{
  "detail": "None is not of type 'integer'",
  "status": 400,
  "title": "Bad Request",
  "type": "about:blank"
}
```

See possibly zalando/connexion#558

**Comment by shuttle1987** [comment]
This issue is quite annoying, we could do with some regression tests here too

**Comment by peek4y** [comment]
This is happening with connexion==2.2.0 version, I'm using OpenAPI specification.
the error messages are very vague, it does not give the exact property name, any idea why?

```
{
  "detail": "'' is too short'",
  "status": 400,
  "title": "Bad Request",
  "type": "about:blank"
}
```

It does not give me the exact property that went wrong, also if we send an empty body, the validation error is same as what OP mentioned.

Is this a regression?
