### ISSUE TITLE
Cannot create multiple corpuses because of duplicate labels

### ISSUE THREAD

**Issue by aapeliv** [persephone-tools/persephone-web-API#160]
It returns an error "Invalid corpus provided" (also see #159). Digging a bit deeper, the error comes from it trying to create new labels each time, but these are marked as unique in SQL.

```
(sqlite3.IntegrityError) UNIQUE constraint failed: label.label [SQL: 'INSERT INTO label (label) VALUES (?)'] [parameters: ('v̩',)] (Background on this error at: http://sqlalche.me/e/gkpj)
```

**Comment by shuttle1987** [comment]
This is definitely a bug, thanks for the error report. There's a definite lack of test cases here which has been caused by a lack of good setup for database based tests and fixtures

**Comment by shuttle1987** [comment]
@aapeliv What sort of input caused this bug to be exposed? I'd like to write a regression test using the exact input you had here.
