### ISSUE TITLE
Enable TravisCI integration

### ISSUE THREAD

**Issue by shuttle1987** [persephone-tools/persephone-web-API#19]
Settings need to be changed in GitHub organization to allow this.

**Comment by oadams** [comment]
What specifically needs to be changed? Travis already has third-party access?

**Comment by shuttle1987** [comment]
Builds need to be enabled for this repository, I think there is a setting for PRs that has to be enabled to do the "build on PR" workflow.

**Comment by oadams** [comment]
OK, I've added Travis CI integrations to this repository. Let me know if it does/doesn't work now.

**Comment by shuttle1987** [comment]
I pushed up a commit to the #15 PR which didn't trigger a build

**Comment by oadams** [comment]
Ok, couldn't find the right switch so I've made you an organization owner.

**Comment by shuttle1987** [comment]
Some settings required changes but this is working now.
