### ISSUE TITLE
Get an ELAN file with all required assets for testing

### ISSUE THREAD

**Issue by shuttle1987** [persephone-tools/persephone-web-API#49]
Having a real ELAN file to test against would make life much easier for development

**Comment by alexis-michaud** [comment]
I can ask colleagues: that should be an easy one. 

What are the required assets? Would you like a set of files with corresponding audio for a complete test tutorial? Or just 1 file to test preprocessing?

**Comment by shuttle1987** [comment]
As far as I understand Elan files have transcriptions with references to the original files. If this is the case I need to have the associated audio files. Even if this is a really small sample file along with the transcriptions this would help me a lot because this is something we would like to support.

This is would also help me with https://github.com/persephone-tools/persephone/issues/178

**Comment by shuttle1987** [comment]
As per emails I now have this, thanks for the assistance. Other collaborators may want to use Chatino data found here: https://gorilla.linguistlist.org/code/ctp/ (licensed as Creative Commons Attribution-ShareAlike 4.0 (CC-BY-SA))
