### ISSUE TITLE
Supply information about which filetypes are accepted by the backend

### ISSUE THREAD

**Issue by shuttle1987** [persephone-tools/persephone-web-API#6]
It might be good to expose information about which filetypes the backend will accept.

**Comment by aapeliv** [comment]
Let me know when you've got a draft API spec for this @shuttle1987

**Comment by shuttle1987** [comment]
My thought was a dictionary that has pairs of operations along with acceptable file types for those.
What do you need here?

**Comment by aapeliv** [comment]
Yeah sounds good to me

**Comment by shuttle1987** [comment]
OK I'll get that done either later today or first thing tomorrow

**Comment by shuttle1987** [comment]
Merged in an interim solution to keep you unblocked. Will have to revisit this later
