### ISSUE TITLE
Unicode normalization

### ISSUE THREAD

**Issue by shuttle1987** [persephone-tools/persephone-web-API#89]
It will be important to deal with this because at the database level we may have situations where there are characters that need to be distinct but end up being repeated due to having different representations.

Much like this issue over on Persephone https://github.com/persephone-tools/persephone/issues/125 I'm strongly considering using NFC form for unicode stored in the database system.

**Comment by shuttle1987** [comment]
@alexis-michaud Thank you for the feedback, I suspected it would be important but this confirms that I'll definitely be using this.

**Comment by alexis-michaud** [comment]
Can't wait to see how it can be implemented. Corpus contributors could provide a simple, 'hard' table of equivalences with the phonetic representation of a phoneme in one column and alternative codings in another. But it would be even more beautiful (and much more complete and robust: 'bug-proof') if it could be automated on the basis of equivalences recognized by the Unicode standard, such as: allowing any order for diacritics (for instance, `ɻ + ̩  + ̃ ` as well as `ɻ + ̃  + ̩ ` to create `ɻ̩̃ `) and recognizing canonical equivalences such as between 'hard-coded' `à` and `a` + diacritic accent.

**Comment by shuttle1987** [comment]
My first thought is to use 9Normalization Form C (NFC)](https://www.unicode.org/reports/tr15/#Norm_Forms) since this is what is suggested here: https://datatracker.ietf.org/doc/rfc5198/?include_text=1

This would allow for an automated process with solid library support behind it, in general since these systems are complex they are best dealt with via libraries and automation.

My general heuristic for now is that characters that are rendered identically will correspond to the same data in the system as much as is possible as I think this will be the easiest to use. (Where "easiest" is defined by this concept https://en.wikipedia.org/wiki/Principle_of_least_astonishment)

**Comment by shuttle1987** [comment]
Need to make sure this is working properly before the workshops, hence adding this to the milestone.

**Comment by alexis-michaud** [comment]
"before the workshops": what a challenge! 👍 👍 

<img src="https://user-images.githubusercontent.com/6072524/48361093-043c8b80-e6a1-11e8-958c-44b76dea69de.png" alt="Why won't this show up?" width="400"/>

@shuttle1987 I am concerned that this new big success within less than 2 weeks (!!:roller_coaster:!!) will constitute a blatant violation of the Principle of Least Astonishment, in contradiction to your stated principles. We're watching, and expecting to be astonished once more :seedling: :deciduous_tree:

**Comment by shuttle1987** [comment]
The database portion of this with the labels is done, next step is to normalize the transcription text files. This incidentally is part of the reason I'd have preferred a text endpoint for the transcription files as it would make operations such as this easier.
