### ISSUE TITLE
Corpus creation endpoint is missing required parameters `label_type` and `feature_type` in API spec

### ISSUE THREAD

**Issue by aapeliv** [persephone-tools/persephone-web-API#90]
See [`api_spec.yaml`](https://github.com/persephone-tools/persephone-web-API/blob/2987593f6f989b6b1a4973ae56884915a0ea0970/persephone_api/api_spec.yaml#L95) and [`corpus.py`](https://github.com/persephone-tools/persephone-web-API/blob/2987593f6f989b6b1a4973ae56884915a0ea0970/persephone_api/api_endpoints/corpus.py#L127)

**Comment by shuttle1987** [comment]
It's particularly annoying that the connexion API generation that's currently being used doesn't actually validate the extra parameters that get passed in. In this case the tests pass but I'd have much preferred to see them fail validation.

If there's some way of making this validation be more strict in testing that would be good. Things like this also show that it would also be good to fuzz the inputs as part of testing.
