### ISSUE TITLE
ffmpeg requirement not documented anywhere

### ISSUE THREAD

**Issue by aapeliv** [persephone-tools/persephone-web-API#91]
It's documented for the persephone library [in the quickstart instructions](https://github.com/persephone-tools/persephone/blob/12939c1a22679d7d493ac7c85876312dcebc67b4/docs/quickstart.rst#1-installation).

**Comment by shuttle1987** [comment]
This is a good catch. We really need to get some installation automation set up for this.

Related issues are #11 #61
